### ISSUE TITLE
Avaliar se todas as causas serão resolvíveis com software. Caso contrário informar quais serão.

### ISSUE THREAD

**Issue by BrunoBReis** [mdsreq-fga-unb/2024.2-T01-CRMProInjecao#33]
Avaliar a causa depois da Lean Inception com o P.O.

**Comment by Stain19** [comment]
# Causas Não Resolvíveis Apenas com Software

De acordo com a solucao proposta e o diagrama de ishikawa, existem algumas causas que o nosso software não resolve diretamente, pois envolvem fatores externos ou humanos:

## Mão de Obra:
 - *Equipe pequena*: Um software não pode resolver diretamente a limitação de mão de obra. Será necessário contratar ou treinar mais pessoas para lidar com o aumento de demanda e tarefas administrativas.
 - *Sem gestão de clientes*: Embora o software crie a estrutura para a gestão de clientes, o processo exige esforço humano para alimentar o sistema e monitorá-lo adequadamente. O sistema não faria a gestão de forma autônoma, logo não resolveria o problema por si só.

## Meio Ambiente:
- *Parceria com uma oficina*: O software não influencia diretamente nas parcerias externas. A empresa precisará gerenciar as relações com parceiros manualmente, ainda que o sistema possa ajudar a organizar informações.

**Comment by Stain19** [comment]
Acha que seria bom adicionar isto ao gitpages na parte de solucao proposta? @BrunoBReis
